import type { Metadata } from "next";
import Navbar from "./(site)/components/Navbar";
import Footer from "./(site)/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className='min-h-screen relative z-10'>
        <div className='fixed top-0 left-0 w-full z-50'>
          <Navbar />
        </div>
        <div className="absolute top-0 left-0 h-[70%] w-full z-0 bg-white bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(80,77,188,0.55),rgba(121,134,255,0.26),rgba(255,255,255,0.0))]"></div>
          {children}
          <Footer />
    </div>
  );
}
